version: '3.9'
services: 
    node:
        container_name: 'proxy'
        build: .
        volumes: 
            - ./nginx:/etc/nginx
        restart: always
        ports: 
            - '3001:3000'
            - '80:80'
            - '8080:8080'
        environment: 
            - DEFAULT_USER=admin
            - DEFAULT_PASSWORD=password