version: '3.9'
services: 
    node:
        container_name: 'load_balancer'
        build: .
        volumes: 
            - ./config:/app/config
        ports: 
            - '3000:3000'
    nginx:
        container_name: 'nginx_load'
        image: nginx:latest
        volumes: 
            - ./config/nginx.conf:/etc/nginx/nginx.conf
        depends_on: 
            - node
        ports: 
            - 80:80
            - 8080:8080

