version: '3.9'
services: 
    node:
        container_name: 'load_balancer'
        build: .
        volumes: 
            - ./nginx:/etc/nginx
        restart: always
        ports: 
            - '3000:3000'
            - '80:80'
            - '8080:8080'